--- #YAML:1.0
name:                Algorithm-KMeans
version:             1.1.1
abstract:            A pure-Perl implementation of K-Means Clustering
license:             ~
author:              
    - Avinash Kak (kak@purdue.edu)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Graphics::GnuplotIF:           1.4
    Math::Random:                  0.71
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
