--- #YAML:1.0
name:               Algorithm-KMeans
version:            1.40
abstract:           A pure-Perl implementation of K-Means Clustering
author:
    - Avinash Kak (kak@purdue.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Graphics::GnuplotIF:  1.4
    Math::GSL:            0.26
    Math::Random:         0.71
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
